#!/usr/bin/env python

import smach
import rospy
import smach_ros

import state_machine_tutorial
from smach_tutorial.AdvancedStateMachine import *
##-----------------------------------------------------------------------------------

def main():
    
    Trajectory_sm = MovingSM()
    
    introspection_server = smach_ros.IntrospectionServer('SM', Trajectory_sm, '/SM_root')
    introspection_server.start()
    
    Trajectory_sm.execute()
    
    introspection_server.stop()


def main1():
    
    FullTrajectory_sm = FullTrajectorySM()
    
    introspection_server = smach_ros.IntrospectionServer('SM', FullTrajectory_sm, '/SM_root')
    introspection_server.start()
    
    FullTrajectory_sm.execute()
    
    introspection_server.stop()
    

if __name__ == '__main__':
    rospy.init_node('tutorial_node')
    exercise = rospy.get_param('tutorial_node/exercise',0) 
    if(exercise == 0):
        main()
    elif(exercise == 1):
        main1()
    else:
        rospy.logerr("Exercise not listed")
            

        
